### ISSUE TITLE
bug: perfomance degradation and memory leak

### ISSUE THREAD

**Issue by PandaWorker** [jsr-core/asyncutil#27]
I noticed a serious problem when using Mutex, with each lock capture, the lock time and memory used grows. This is due to the fact that waiters are not cleared and a full copy of all waiters is made for each capture.

In the example, I just copied the Mutex code and made getter waiters to see if they were accumulating

If the first thousand captures spend about 26.53ms, then the thirtieth thousand is already 1574.99ms.

```ts
import { Mutex } from './Mutex.ts';
import process from 'node:process';

const mutex = new Mutex();

async function step() {
	for (var i = 0; i < 1000; i++) {
		using lock = await mutex.acquire();
	}
}

async function main() {
	for (var i = 0; i < 40; i++) {
		const prefix = `${i}`;

		console.log(`[${prefix}] start:`, process.memoryUsage());

		const startTime = performance.now();
		await step();
		const endTime = performance.now();

		// With each iteration, the time increases by about 10-15%
		console.log(`[${prefix}] time:`, (endTime - startTime).toFixed(2));
		console.log(`[${prefix}] end:`, process.memoryUsage());
	}
}

main();
```

**Comment by lambdalisue** [comment]
@PandaWorker Thanks a lot. Fixed version v1.0.1 is released 👍
