### ISSUE TITLE
Get number of current locks in semaphore

### ISSUE THREAD

**Issue by alexgleason** [jsr-core/asyncutil#43]
I have a semaphore of size 4. I think all 4 of them are getting locked up at the same time, then once one is freed the queue drains:

![image](https://github.com/user-attachments/assets/da9a669f-4733-44d1-9384-53d25509ed35)

(this green line should not be behaving like that)

I would just like if I could call `semaphore.lockedSize` or something to get the number that are currently locked (or the number that are currently idle), so I can make a graph of it and prove my theory.

**Comment by lambdalisue** [comment]
@alexgleason Could you try #44?
